---
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: 'v5.0.0'
    hooks:
      - id: 'trailing-whitespace'
      - id: 'end-of-file-fixer'
      - id: 'check-yaml'
      - id: 'check-added-large-files'
      - id: 'check-merge-conflict'
  - repo: 'https://github.com/ansible-community/ansible-lint.git'
    rev: 'v25.1.0'
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
  - repo: 'https://github.com/Thulium-Drake/pre-commit-hooks'
    rev: '0.0.2'
    hooks:
      - id: 'ansible-sign'
